### ISSUE TITLE
Democratic Autocracy Ruler Bug

### ISSUE THREAD

**Issue by WizOG** [Dukko/mergerofmods#27]
**Describe the bug**
When using the Democratic Autocracy Goverment type, When you first load up the game, Your ruler will be removed when promted to select traits for said ruler, This happens continusly through the game with the ruler getting removed when prompted to add more traits.

After ruler gets removed Spammed with pop ups asking to select traits for Ruler, but due to no ruler being in power, stays on the screen.
![image](https://user-images.githubusercontent.com/83974330/118299153-4c3e0280-b4d8-11eb-89df-5025a667fafd.png)
![image](https://user-images.githubusercontent.com/83974330/118299241-6972d100-b4d8-11eb-98c2-210e34697dc8.png)

**To Reproduce**
- Goverment type : Democratic Autocracy
**Expected behavior**
For the traits to be added and the ruler stays in power
**Screenshots**

**Collection info (please complete the following information):**
 - 0.8.7.5

**Additional context**
To be able to fix this ingame, Use the reform goverment type edict as it changes the goverment, or just reform the goverment into a different authority stance

**Comment by Dukko** [comment]
Should be solved in 1.0. Can you confirm?

**Comment by bladex1200** [comment]
Still seeing this as of 1.0 release last night, same issue

**Comment by p33tz0** [comment]
Can confirm that this is still happening as of the latest 1.0 hotfix release.

**Comment by Dukko** [comment]
Unfortunately, I need to remove this mod. It's causing more conflicts that it benefits
